# This is a basic workflow to help you get started with Actions

name: Construcción

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: '0.9.4'
    
    # Mi nueva acción, su construcción es inminente
    - name: Construcción del paquete
      id: building  
      uses:  VTacius/action-setuptool-rust@v0.8.0
    
    # Ponemos a disposición el artefacto, paso previo para subir el asset a un nuevo release
    - name: Subir el nuevo artefacto
      id: uploading
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.building.outputs.nombre_paquete }}
        path: ${{ steps.building.outputs.ruta_paquete }}
